name: run linting & tests

on:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: install dependencies
        run: python3 -m pip install poetry pre-commit
      - name: install dependencies
        run: |
          poetry install
          pre-commit install --install-hooks
      - name: run pre-commit
        run: pre-commit run --all
      - name: pytest
        run: poetry run pytest
        env:
          CHURCHTOOLS_URL: ${{ secrets.CHURCHTOOLS_URL }}
          CHURCHTOOLS_USER: ${{ secrets.CHURCHTOOLS_USER }}
          CHURCHTOOLS_PASSWORD: ${{ secrets.CHURCHTOOLS_PASSWORD }}
